// Generated by gencpp from file locmap/LocMapLocation.msg
// DO NOT EDIT!


#ifndef LOCMAP_MESSAGE_LOCMAPLOCATION_H
#define LOCMAP_MESSAGE_LOCMAPLOCATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/PoseStamped.h>

namespace locmap
{
template <class ContainerAllocator>
struct LocMapLocation_
{
  typedef LocMapLocation_<ContainerAllocator> Type;

  LocMapLocation_()
    : header()
    , pose()
    , name()
    , group()  {
    }
  LocMapLocation_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pose(_alloc)
    , name(_alloc)
    , group(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _group_type;
  _group_type group;





  typedef boost::shared_ptr< ::locmap::LocMapLocation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::locmap::LocMapLocation_<ContainerAllocator> const> ConstPtr;

}; // struct LocMapLocation_

typedef ::locmap::LocMapLocation_<std::allocator<void> > LocMapLocation;

typedef boost::shared_ptr< ::locmap::LocMapLocation > LocMapLocationPtr;
typedef boost::shared_ptr< ::locmap::LocMapLocation const> LocMapLocationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::locmap::LocMapLocation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::locmap::LocMapLocation_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::locmap::LocMapLocation_<ContainerAllocator1> & lhs, const ::locmap::LocMapLocation_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pose == rhs.pose &&
    lhs.name == rhs.name &&
    lhs.group == rhs.group;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::locmap::LocMapLocation_<ContainerAllocator1> & lhs, const ::locmap::LocMapLocation_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace locmap

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::locmap::LocMapLocation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::locmap::LocMapLocation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::locmap::LocMapLocation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::locmap::LocMapLocation_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::locmap::LocMapLocation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::locmap::LocMapLocation_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::locmap::LocMapLocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9db4e1ca22b055ae17262848c33aa6fa";
  }

  static const char* value(const ::locmap::LocMapLocation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9db4e1ca22b055aeULL;
  static const uint64_t static_value2 = 0x17262848c33aa6faULL;
};

template<class ContainerAllocator>
struct DataType< ::locmap::LocMapLocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "locmap/LocMapLocation";
  }

  static const char* value(const ::locmap::LocMapLocation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::locmap::LocMapLocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"geometry_msgs/PoseStamped pose\n"
"string name\n"
"string group\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::locmap::LocMapLocation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::locmap::LocMapLocation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pose);
      stream.next(m.name);
      stream.next(m.group);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LocMapLocation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::locmap::LocMapLocation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::locmap::LocMapLocation_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "group: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.group);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCMAP_MESSAGE_LOCMAPLOCATION_H
