// Generated by gencpp from file locmap/LocMapGoto.msg
// DO NOT EDIT!


#ifndef LOCMAP_MESSAGE_LOCMAPGOTO_H
#define LOCMAP_MESSAGE_LOCMAPGOTO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace locmap
{
template <class ContainerAllocator>
struct LocMapGoto_
{
  typedef LocMapGoto_<ContainerAllocator> Type;

  LocMapGoto_()
    : header()
    , location_name()  {
    }
  LocMapGoto_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , location_name(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _location_name_type;
  _location_name_type location_name;





  typedef boost::shared_ptr< ::locmap::LocMapGoto_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::locmap::LocMapGoto_<ContainerAllocator> const> ConstPtr;

}; // struct LocMapGoto_

typedef ::locmap::LocMapGoto_<std::allocator<void> > LocMapGoto;

typedef boost::shared_ptr< ::locmap::LocMapGoto > LocMapGotoPtr;
typedef boost::shared_ptr< ::locmap::LocMapGoto const> LocMapGotoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::locmap::LocMapGoto_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::locmap::LocMapGoto_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::locmap::LocMapGoto_<ContainerAllocator1> & lhs, const ::locmap::LocMapGoto_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.location_name == rhs.location_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::locmap::LocMapGoto_<ContainerAllocator1> & lhs, const ::locmap::LocMapGoto_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace locmap

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::locmap::LocMapGoto_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::locmap::LocMapGoto_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::locmap::LocMapGoto_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::locmap::LocMapGoto_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::locmap::LocMapGoto_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::locmap::LocMapGoto_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::locmap::LocMapGoto_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a2a536bbdbeabd2be949e6fb00d6394b";
  }

  static const char* value(const ::locmap::LocMapGoto_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa2a536bbdbeabd2bULL;
  static const uint64_t static_value2 = 0xe949e6fb00d6394bULL;
};

template<class ContainerAllocator>
struct DataType< ::locmap::LocMapGoto_<ContainerAllocator> >
{
  static const char* value()
  {
    return "locmap/LocMapGoto";
  }

  static const char* value(const ::locmap::LocMapGoto_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::locmap::LocMapGoto_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"string location_name\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::locmap::LocMapGoto_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::locmap::LocMapGoto_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.location_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LocMapGoto_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::locmap::LocMapGoto_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::locmap::LocMapGoto_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "location_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.location_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCMAP_MESSAGE_LOCMAPGOTO_H
