# MQTT
MQTT_GP_TOPIC: "hospital/gp/available"
MQTT_USR_TOPIC: "USR"
MQTT_PATIENT_TOPIC: "hospital/patient/register"
MQTT_PAIRING_TOPIC: "hospital/pairing"

# ROS
INIT_POSE_TOPIC: "/initialpose"
STATUS_TOPIC: "/move_base/status"
END_GOAL_TOPIC: "/move_base/cancel"

# ROS Custom
STATE_TOPIC: "/lodestone/state"
LOG_TOPIC: "/dropplot/logs"
GOTO_TOPIC: "/locmap/goto"
LOCATIONS_TOPIC: "/locmap/locations"

USR_MIN: 0
USR_MAX: 1
USR_THRESHOLD: 0.6
USR_PING_DURATION: 1.0

GP_COUNT: 5
GP_PREFIX: "GP-"

LOC_NAME_ENTRANCE: "Entrance"
LOC_NAME_WAITING_ROOM: "Waiting-room"

WAITING_TIME_MAX: 1.5