# MQTT
MQTT_GP_TOPIC: "GPS"
MQTT_USR_TOPIC: "USR"
MQTT_PATIENT_TOPIC: "PATIENT"

# ROS
INIT_POSE_TOPIC: "/initialpose"
STATUS_TOPIC: "/move_base/status"

STATE_TOPIC: "/lodestone/state"

USR_MIN: 0
USR_MAX: 1
USR_THRESHOLD: 0.6
USR_PING_DURATION: 1.0

GP_COUNT: 5
GP_PREFIX: "GP-"

LOC_NAME_ENTRANCE: "Enterance"
LOC_NAME_WAITING_ROOM: "Waiting-room"